var data = [
    [
        {
            "projectImage":"news-img-1.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-2.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-3.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-4.jpg",
            "projectTitle":"优秀学员作品展示"
        }
    ],
    [
        {
            "projectImage":"news-img-5.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-6.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-7.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-4.jpg",
            "projectTitle":"优秀学员作品展示"
        }
    ],
    [
        {
            "projectImage":"news-img-3.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-2.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-6.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-5.jpg",
            "projectTitle":"优秀学员作品展示"
        }
    ],
    [
        {
            "projectImage":"news-img-4.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-2.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-3.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-1.jpg",
            "projectTitle":"优秀学员作品展示"
        }
    ],
    [
        {
            "projectImage":"news-img-7.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-6.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-5.jpg",
            "projectTitle":"优秀学员作品展示"
        },
        {
            "projectImage":"news-img-4.jpg",
            "projectTitle":"优秀学员作品展示"
        }
    ]
]